### PR TITLE
Fix(RNGiphyDialog): launch error when rootViewController is nil

### LINKED ISSUE #19: Error on launch IOS
Hi, i have a problem with giphy-react-native-sdk in IOS. Build works fine but when launching my app, it stucks on launchscreen and i got log error : "Fatal error: Unexpectedly found nil while unwrapping an Optional value: file giphy_react_native_sdk/RNGiphyDialog.swift, line 60"

Can you help me please ?

### PR DESCRIPTION
**Pull request by pshoniuk**
Closes #19

### CODE REVIEW

File: ios/RNGiphyDialog.swift [hunk 1]
```diff
@@ -90,9 +89,10 @@ open class RNGiphyDialog: RCTEventEmitter, GiphyDelegate {
   open func show() -> Void {
     DispatchQueue.main.async {
       let giphy = GiphyViewController()
+      let rootViewController = UIApplication.shared.windows.first?.rootViewController
       giphy.applyRNConfig(self.config)
       giphy.delegate = self
-      self.rootViewController.present(giphy, animated: true, completion: {
+      rootViewController?.present(giphy, animated: true, completion: {
         self.giphyViewController = giphy
```
Comment (ALexanderLonsky) [inline ios/RNGiphyDialog.swift:96]: I think it requires 
```
completion: { [weak self] in
self?.giphyViewController = giphy
```

otherwise it might be a strong reference to self that lead to reference cycle

**Review by ALexanderLonsky — APPROVED** [review]
